### ISSUE TITLE
Do you wanna collab on making this Realtime?

### ISSUE THREAD

**Issue by mhamdanx** [skeskinen/resemble-denoise-onnx-inference#2]
Nice work done here...
Are you interested in collaborating and making this real-time model? 
I love the performance of model, accuracy wise, but it's not very usable in real-time apps. 
I would like to shrink this to 5MB. (~10ms)

**Comment by skeskinen** [comment]
Not really interested. But I think it can already run in real time on GPU. On a CPU it's a little tight but maybe possible with some tweaks.
